### ISSUE TITLE
Question: what's the relation with "projectatomic/rpmdistro-gitoverlay"?

### ISSUE THREAD

**Issue by TomasTomecek** [rpm-software-management/rpm-gitoverlay#23]
I'm confused, how is this project related to https://github.com/projectatomic/rpmdistro-gitoverlay? Same goal, different implementation?

**Comment by Conan-Kudo** [comment]
@TomasTomecek `rpmdistro-gitoverlay` is a source-git type system, `rpm-gitoverlay` supports both source-git and dist-git styles.

**Comment by TomasTomecek** [comment]
Thanks, Neal!
