### ISSUE TITLE
Python 2.7+ and 3.4+ support

### ISSUE THREAD

**Issue by cz172638** [rpm-software-management/rpm-gitoverlay#5]
some older distributions like RHEL6/7 have only python2

**Comment by igor-raits** [comment]
We are using:

**3.5**:
- Function: `subprocess.run()`

**3.4**:
- Module: `enum`

**3.2**:
- Function `tempfile.TemporaryDirectory()`

**Comment by cz172638** [comment]
for enum - https://pypi.python.org/pypi/enum34

**Comment by lukash** [comment]
Python 2 support doesn't really make sense anymore...
